### ISSUE TITLE
Your Score

### ISSUE THREAD

**Issue by zjedwin** [camples/SQLFROMSCRATCH#1]
### Criteria 1: Report
* _Score Level:_ 3
* _Comment(s):_ Most responses are well explained and the supporting graphs are well constructed. However, no conclusion is stated.
 
### Criteria 2: Query Accuracy
* _Score Level:_ 4
* _Comment(s):_ The queries accurately produce the results expected by the assignment.
 
### Criteria 3: Query Formatting
* _Score Level:_ 4
* _Comment(s):_ The queries are consistently formatted according to the [Codecademy style guide](https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf).
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 3
* _Comment(s):_ Since the report is not complete, I can only judge that the report demonstrates a partial understanding of the material in the assignment.

 ### Overall Score: 14/16
Overall, the project has the beginnings of what's expected but you need to close with a conclusion. There are a few other things that I recommend. 
1. A brief slide introducing Codeflix and their objective with this study would be nice.
2. Expand on slides 4 and 6 by presenting some of the relevant tables and discuss them in some more detail.
3. Break the final slide into two since the final graph falls off the screen.

**Comment by camples** [comment]
Thanks for the input.
